[SERVICE]
    Flush        5
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name         tail
    Path         /var/log/*.log
    Tag          host.*
    DB           /fluent-bit/logs.db
    Parser       docker

[OUTPUT]
    Name         es
    Match        host.*
    Host         elasticsearch
    Port         9200
    Index        fluentbit
    Type         _doc

[INPUT]
    Name             winlog
    Channels         Application,System,Security
    Interval_Sec     5
